### ISSUE TITLE
[7.0][mass_editing] TypeError: 'int' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by moylop260** [OCA/server-tools#24] opened 2014-07-22 15:58 UTC
Steps to reproduce issue:
![templates - openerp - mass editing bug al elegir campos](https://cloud.githubusercontent.com/assets/6644187/3660481/2cc5aa2c-11b8-11e4-8cbf-fb43715535b4.png)

Error:

``` python
Server Traceback (most recent call last):
  File "/server/openerp/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/server/openerp/netsvc.py", line 296, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/server/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, *params)
  File "/server/openerp/osv/osv.py", line 190, in execute_kw
    return self.execute(db, uid, obj, method, *args, **kw or {})
  File "/server/openerp/osv/osv.py", line 132, in wrapper
    return f(self, dbname, *args, **kwargs)
  File "/server/openerp/osv/osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, *args, **kw)
  File "/server/openerp/addons/audittrail/audittrail.py", line 532, in execute_cr
    return fct_src(cr, uid, model, method, *args, **kw)
  File "/server/openerp/osv/osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/server/openerp/addons/mass_editing/mass_editing.py", line 38, in search
    'model_id', 'in', map(int, domain[2][1:-1].split(',')))]
TypeError: 'int' object has no attribute '__getitem__'
```

I expected a view with fields view.

**Comment by eLBati** [comment] 2014-07-23 07:30
Hello,
this is a duplicate of https://github.com/OCA/server-tools/issues/15

**Closed as completed** 2014-09-22 15:19 UTC
Labels: duplicate
