### ISSUE TITLE
[11.0] [scheduler_error_mailer] Callback Error

### ISSUE THREAD

**Issue by AjayViknesh** [OCA/server-tools#1537] opened 2019-04-02 05:05 UTC
Hi I installed the module and ran the demo schedule action. I got this error in the terminal.

Kindly please help me with this issue I am not able resolve it.

`2019-04-02 05:03:52,146 11292 ERROR B2Btesting odoo.addons.base.ir.ir_cron: Call from cron Test Scheduler Error Mailer for server action #554 failed in Job #31
Traceback (most recent call last):
  File "/home/ewall-lap/Desktop/odoo-isha-b2b/odoo/addons/base/ir/ir_cron.py", line 102, in _callback
    self.env['ir.actions.server'].browse(server_action_id).run()
  File "/home/ewall-lap/Desktop/odoo-isha-b2b/odoo/addons/base/ir/ir_actions.py", line 544, in run
    res = func(action, eval_context=eval_context)
  File "/home/ewall-lap/Desktop/odoo-isha-b2b/addons/website/models/ir_actions.py", line 57, in run_action_code_multi
    res = super(ServerAction, self).run_action_code_multi(action, eval_context)
  File "/home/ewall-lap/Desktop/odoo-isha-b2b/odoo/addons/base/ir/ir_actions.py", line 420, in run_action_code_multi
    safe_eval(action.sudo().code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/home/ewall-lap/Desktop/odoo-isha-b2b/odoo/tools/safe_eval.py", line 348, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/ewall-lap/Desktop/odoo-isha-b2b/addons/scheduler_error_mailer/models/ir_cron.py", line 55, in _test_scheduler_failure
    _("Task failure with UID = %d.") % self._uid)
odoo.exceptions.UserError: ('Task failure with UID = 1.', '')
2019-04-02 05:03:52,175 11292 ERROR B2Btesting odoo.addons.base.ir.ir_cron: Unexpected exception while processing cron job {'user_id': 1, 'doall': True, 'numbercall': 1, 'email_template_id': 94, 'interval_number': 1, 'write_date': '2019-04-02 04:52:19.404311', 'active': True, 'ir_actions_server_id': 554, 'create_date': '2019-04-02 04:22:49.838118', 'priority': 5, 'id': 31, 'nextcall': '2019-04-02 04:23:10', 'create_uid': 1, 'interval_type': 'minutes', 'cron_name': 'Test Scheduler Error Mailer', 'write_uid': 1}
Traceback (most recent call last):
  File "/home/ewall-lap/Desktop/odoo-isha-b2b/odoo/addons/base/ir/ir_cron.py", line 102, in _callback
    self.env['ir.actions.server'].browse(server_action_id).run()
  File "/home/ewall-lap/Desktop/odoo-isha-b2b/odoo/addons/base/ir/ir_actions.py", line 544, in run
    res = func(action, eval_context=eval_context)
  File "/home/ewall-lap/Desktop/odoo-isha-b2b/addons/website/models/ir_actions.py", line 57, in run_action_code_multi
    res = super(ServerAction, self).run_action_code_multi(action, eval_context)
  File "/home/ewall-lap/Desktop/odoo-isha-b2b/odoo/addons/base/ir/ir_actions.py", line 420, in run_action_code_multi
    safe_eval(action.sudo().code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/home/ewall-lap/Desktop/odoo-isha-b2b/odoo/tools/safe_eval.py", line 348, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/ewall-lap/Desktop/odoo-isha-b2b/addons/scheduler_error_mailer/models/ir_cron.py", line 55, in _test_scheduler_failure
    _("Task failure with UID = %d.") % self._uid)
odoo.exceptions.UserError: ('Task failure with UID = 1.', '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ewall-lap/Desktop/odoo-isha-b2b/odoo/addons/base/ir/ir_cron.py", line 223, in _process_jobs
    registry[cls._name]._process_job(job_cr, job, lock_cr)
  File "/home/ewall-lap/Desktop/odoo-isha-b2b/odoo/addons/base/ir/ir_cron.py", line 138, in _process_job
    cron._callback(job['cron_name'], job['ir_actions_server_id'], job['id'])
  File "/home/ewall-lap/Desktop/odoo-isha-b2b/odoo/addons/base/ir/ir_cron.py", line 111, in _callback
    self._handle_callback_exception(cron_name, server_action_id, job_id, e)
TypeError: _handle_callback_exception() missing 1 required positional argument: 'job_exception'
`

Thanks!

**Comment by pedrobaeza** [comment] 2019-04-02 07:54
@AMhadhbi you migrated the module to v11. Can you please check?

**Comment by AjayViknesh** [comment] 2019-04-03 07:00
Hi!

Even if I raise any other error other than the given example in the module I am getting the same error

`TypeError: _handle_callback_exception() missing 1 required positional argument: 'job_exception'`

Is there any other way to overcome this.

Thanks!

**Comment by AMhadhbi** [comment] 2019-04-03 08:46
@pedrobaeza @AjayViknesh 
I created new empty demo database and I installed the module and ran the demo schedule action, there is no issue triggered , so I cannot reproduce the issue. we already used the module and we don't have this issue.
@AjayViknesh please test the module with new empty demo database with the latest update odoo v11.

**Comment by pedrobaeza** [comment] 2019-04-03 08:56
Thanks for the insights, @AMhadhbi. Closing this while no other explanations provided.

**Closed as completed by pedrobaeza** 2019-04-03 08:56 UTC
