### ISSUE TITLE
[10] inactive_session_time_out_delay Value Error

### ISSUE THREAD

**Issue by Camille1616** [OCA/server-tools#1099] opened 2017-12-20 10:26 UTC
When entering an character instead of an digit in the value field there will appear a "permission denied" error.

**Comment by yajo** [comment] 2018-01-30 09:25
Closing due to lack of information. Please provide steps to reproduce and full logs. Feel free to reopen if you do. Thanks!

**Closed as completed by yajo** 2018-01-30 09:25 UTC
