### ISSUE TITLE
V9 broken

### ISSUE THREAD

**Issue by simahawk** [OCA/server-tools#1011] opened 2017-10-05 09:03 UTC
@lasley sounds like 9.0 is broken because of https://travis-ci.org/OCA/server-tools/jobs/282692962#L1764-L1780

**Comment by lasley** [comment] 2017-10-05 14:50
@sylvain-garancher - any thoughts on this one? It's kind of weird that the test outright broke, instead of one of the standard cursor closed/timeout issues we've been seeing.

**Comment by Garamotte** [comment] 2017-10-05 14:57
I'm looking at it, but I didn't found the root cause yet.

**Comment by Garamotte** [comment] 2017-10-05 15:55
Ok, found the issue, this is my mistake: I forgot to fix the `oauthlib` version in `requirements.txt`, sorry :(

Everything works well with `oauthlib==2.0.0`, but the test fails with `oauthlib==2.0.4`, because they changed the returned error. This is now a 400 (bad request) in case the redirect URI is wrong or missing, instead of the previous 401 (unauthorized): https://github.com/idan/oauthlib/commit/dc8aa1f60b93c120d9594c00b250cb0d95edc7b2

I think the best is to put `oauthlib==2.0.0` in the `requirements.txt` file.

**Comment by lasley** [comment] 2017-10-05 15:59
What if we just look for one of the two errors?

**Comment by lasley** [comment] 2017-10-05 15:59
IMO sticking the version to an old number will just make someone else, probably one of us, fix it later right?

**Comment by lasley** [comment] 2017-10-05 16:00
Maybe we stick it for v9 and I fix it in 10?

**Comment by Garamotte** [comment] 2017-10-06 04:10
I think it's better to keep the version used to develop the module on 9.0, if someone already used it, to avoid potential other behaviour changes. Maybe add a comment in the test, in case someone hits the issue again, to avoid spending time on an already resolved issue ;)

For the v10.0, update the lib of course ;)

**Comment by sbidoul** [comment] 2017-10-06 14:57
@sylvain-garancher is it possible to make the code compatible with both versions of oauthlib?

**Comment by simahawk** [comment] 2017-10-06 15:22
:+1: @sbidoul. If that's the only exception maybe you can check the package version (or rely on kind of response) and make it work w/ both versions and forget about double version maintenance.

**Comment by lasley** [comment] 2017-10-06 16:30
That was my plan in v10, so we can just backport the change

**Comment by Garamotte** [comment] 2017-10-06 16:31
As this is a simple error code check, we can check for 400 or 401, the behaviour is the same for our module.
A fix in the test to accept both versions would be to replace the assert by `self.assertIn(response.status_code, (400, 401))`.
I think the next assert should be updated too, by using `assertIn`, or two `assertEqual` with an `if response.status_code`.

**Comment by pedrobaeza** [comment] 2017-10-11 17:15
Is this solved?

**Comment by lasley** [comment] 2017-10-11 23:08
I haven't gotten to anything on my side yet for this - admittedly been down a rabbit hole with web hooks the past few days, and I'm too damned stubborn to stop now.

**Comment by Garamotte** [comment] 2017-10-21 21:56
I just created a PR to fix this issue: https://github.com/OCA/server-tools/pull/1034

**Comment by pedrobaeza** [comment] 2017-12-21 09:58
Closing as the PR is merged.

**Closed as completed by pedrobaeza** 2017-12-21 09:58 UTC
Labels: bug
