### ISSUE TITLE
[10.0] Audit trail logs - Errors on read

### ISSUE THREAD

**Issue by maclarensg** [OCA/server-tools#747] opened 2017-02-27 01:13 UTC
When create an audit log rule with log read enable,

The following error appears

```
2017-02-27 01:01:53,853 17231 ERROR asme odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/gavinyap/Documents/gitlab/asme/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/gavinyap/Documents/gitlab/asme/odoo/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/home/gavinyap/Documents/gitlab/asme/odoo/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/gavinyap/Documents/gitlab/asme/odoo/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/gavinyap/Documents/gitlab/asme/odoo/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/gavinyap/Documents/gitlab/asme/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/gavinyap/Documents/gitlab/asme/odoo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/home/gavinyap/asme/odoo/addons/web/controllers/main.py", line 878, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/gavinyap/asme/odoo/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/gavinyap/Documents/gitlab/asme/odoo/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/gavinyap/Documents/gitlab/asme/odoo/odoo/api.py", line 670, in call_kw_multi
    recs = self.with_context(context or {}).browse(ids)
  File "/home/gavinyap/Documents/gitlab/asme/odoo/odoo/models.py", line 4865, in with_context
    context = dict(args[0] if args else self._context, **kwargs)
ValueError: dictionary update sequence element #0 has length 9; 2 is required
```

**Step to produce**
1) Install Note, Audit trail
2) Create log rule on Note object with log read
3) Create a note in kanban
4) Error appears

**Comment by arafatx** [comment] 2017-06-05 00:55
Related issue here. No solution yet https://github.com/OCA/server-tools/issues/822#issue-224668073

**Comment by arafatx** [comment] 2017-08-21 04:22
Not sure what have been changed when I updated the Odoo version, this one got solved.

**Comment by pedrobaeza** [comment] 2017-08-21 07:06
Closing then.

**Closed as completed by pedrobaeza** 2017-08-21 07:06 UTC
Labels: bug, help wanted

**Comment by anniquetapha** [comment] 2017-08-22 12:44
@arafatx i am having the same issue and i already have the odoo 10 installed. What else did you update because i can not seem to fix this issue

**Comment by anniquetapha** [comment] 2017-08-22 12:46
@pedrobaeza if you know what solved this issue, can you please explain it because I am not seeing any solution in this thread. Please help

**Comment by pedrobaeza** [comment] 2017-08-22 14:05
@Annique15, update as stated. If not, you should reproduce the error on runbot and put in another issue the steps to reproduce the problem.

**Comment by anniquetapha** [comment] 2017-08-24 15:29
@pedrobaeza   I already created an issue. Here is the link https://github.com/OCA/server-tools/issues/946
